### ISSUE TITLE
New Path Globbing not working for Date_range

### ISSUE THREAD

**Issue by Deathbot64** [nwithan8/plex-prerolls#12]
[preroll.config.txt](https://github.com/user-attachments/files/17773777/preroll.config.txt)
I cant get the system to see the path for date_range no matter how I have it configured

**Comment by nwithan8** [comment]
Bug fixed, will be in v3.0.1, releasing to Docker now.

**Comment by Deathbot64** [comment]
Sorry, forgot to follow and thank you. This is awesome
