### ISSUE TITLE
running script error.

### ISSUE THREAD

**Issue by shedman214** [nwithan8/plex-prerolls#2]
I'm trying to manually run the python script, but i keep running into this error in unraid console:
![image](https://github.com/nwithan8/plex-prerolls/assets/32603273/d3a56c9b-e752-453a-9f4b-72ee4ae86f39)

**Comment by nwithan8** [comment]
As the error suggests, no file exists at `/mnt/user/appdata/prerolls/config.yaml`.

I also would advise against running this Python script on Unraid. Use the Docker container instead: https://unraid.net/community/apps?q=prerolls#r
