### ISSUE TITLE
Invalid compose.yml

### ISSUE THREAD

**Issue by benawhite** [nwithan8/plex-prerolls#5]
https://github.com/nwithan8/plex-prerolls/blob/9941831407ac1f09f4639c3de6cbbd3003214ea7/docker-compose.yml#L6

I believe this line should be changed to 
`- /path/to/config:/config`

**Comment by camrionnvmff** [comment]
The 6th line in the docker-compose.yml file you mentioned does have an issue. This line should be taken from

- /path/to/config:/
Change to

- /path/to/config:/config
The reason for this modification is that Docker Compose requires specifying the target path within the container for volume mounting. The original version only specified the path/path/to/config of the host computer, but did not specify the path within the container, which would result in invalid configuration files.

You can try modifying the docker-compose.yml file and running Docker Compose again:
version: '3'
services:
your-service-name:
image: your-image-name
volumes:
- /path/to/config:/config
I hope this can solve your problem. If there are still issues, please redeploy the development environment using Servbay

**Comment by nwithan8** [comment]
Not sure what that spam response was. Thanks for reporting.
