### ISSUE TITLE
Path Globbing per Rule/Schedule

### ISSUE THREAD

**Issue by Deathbot64** [nwithan8/plex-prerolls#9]
I am running this in Docker for Windows with Plex running in windows. I can get the always rule set up but I want to use videos in different drives/folders outside of my pre rolls (trying to set up full movie pre rolls as a joke on specific days) but with the way Path Globbing is current set it I cant change the paths per rules. Is this something you could add?

**Comment by nwithan8** [comment]
Good idea, I'll look at adding that, thanks!

**Comment by Deathbot64** [comment]
No Thank you for making this

**Comment by nwithan8** [comment]
This is out in v3.0.0, populating to Docker Hub currently.

**Comment by Deathbot64** [comment]
So the new path globbing is working for the always setting but the path globbing doesnt seem to work work the date range options

`# All keys must be in lowercase
# All paths will be case-sensitive based on your environment (Linux, Windows)

plex:
  url: http://xxx:32400 # URL to your Plex server
  token: xxx # Your Plex token

# Always include these pre-rolls
always:
  enabled: true
  #paths:
   # - "/V/Pre Roll Video/Adult Swim Plex.mp4"
    #- "/V/Pre Roll Video/Adult Swim Plex v2.mp4"
  path_globbing:
        enabled: true
        pairs:
          - root_path: /V/Pre Roll Video
            plex_path: V:\Pre Roll Video
            patterns:
              - "/V/Pre Roll Video/*.mp4"
              - "/V/Pre Roll Video/*.mkv"
  count: 1 # Optional, randomly select X many videos from the list rather than all of them
  weight: 1 # Optional, how much to emphasize these pre-rolls over others (higher = more likely to play)
  
# Schedule prerolls by date and time frames
date_range:
  enabled: true
  ranges:
    - name: "Groundhog's Day" # Optional name for logging purposes
      start_date: xxxx-11-14 # Jan 1st, 2020
      end_date: xxxx-11-14 # Jan 2nd, 2020
      #paths:
       # - "/K/Movies/Groundhog Day 1993/Groundhog Day 1993 Bluray-1080p.mp4"
      path_globbing:
            enabled: true
            pairs:
              - root_path: /K/Movies/Groundhog Day 1993
                plex_path: K:\Movies\Groundhog Day 1993
                patterns:
                  - "/K/Movies/Groundhog Day 1993/*.mp4"
                  - "/K/Movies/Groundhog Day 1993/*.mkv"
      count: 1
      disable_always: true # Optional, if present and true, disable the always prerolls when this schedule is active`

**Comment by nwithan8** [comment]
Moving discussion to #12
